services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app-dev
    restart: unless-stopped
    user: node
    volumes:
      - ../:/workspaces/app:cached
      - node_modules:/workspaces/app/node_modules
    tty: true
    stdin_open: true
    command: sleep infinity

volumes:
  node_modules:
